export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    appTitle: "PAEONIX",
    browse: "Browse",
    aiAssistant: "AI Assistant",
    saved: "Saved",
    adminHub: "Admin Hub",
    settings: "Settings",
    clinicalEncyclopedia: "Clinical Encyclopedia",
    verifiedSource: "★ Verified Source",
    dailyFocus: "Daily Clinical Focus",
    dailyFocusTitle: "Cardiovascular Wellness & Lipids",
    dailyFocusDesc: "Explore how diet, organic lipids, and physical activity optimize cellular endurance and guard vital capillary elasticity.",
    learnMore: "Learn More",
    connecting: "Connecting securely to medical records...",
    allTopics: "All Topics",
    chronicConditions: "Chronic Conditions",
    cardioHealth: "Cardiovascular Health",
    generalWellness: "General Wellness",
    infectiousDiseases: "Infectious Diseases",
    mentalHealth: "Mental Health",
    searchPlaceholder: "Search symptoms, conditions, medications...",
    bookmarkTabTitle: "Saved Resource Library",
    bookmarkTabDesc: "Your curated repository of medical reference material",
    noSavedTitle: "No Saved Reference Articles",
    noSavedDesc: "Read articles in the Browse tab and click the bookmark icon to save them for offline medical reference.",
    chatHeader: "PAEONIX AI Educational Agent",
    chatSub: "Trusted Clinical Medical Answers",
    chatPlaceholder: "Ask about symptoms, prevention, or medical terminology...",
    chatDisclaimer: "Disclaimer: This educational tool is not a substitute for professional clinical advice, diagnosis, or treatment.",
    appSettings: "App Settings",
    managePrefs: "Manage PAEONIX preferences",
    themeCustomization: "Theme Customization",
    langRegional: "Language & Regional",
    preferredLang: "Preferred Language",
    pushNotifications: "Push Notifications",
    notifyDesc: "Receive alerts on medical updates",
    accountSecurity: "Account Security",
    changePwd: "Change Security Password",
    currentPwd: "Current Password",
    newPwd: "New Password",
    confirmNewPwd: "Confirm New",
    updatePwd: "Update Password",
    signOut: "Sign Out from PAEONIX",
    buildVersion: "Platform Build version:",
    emailPlaceholder: "Patient Email Address",
    pwdPlaceholder: "Security Password",
    dontHaveAccount: "Don't have a secure patient account?",
    alreadyHaveAccount: "Already registered?",
    createAccount: "Create Patient Record",
    loginHeader: "Access Secure Patient Portal",
    signupHeader: "Register Secure Clinical Profile",
    oauthOption: "Or sign in securely via verified providers",
    signUpEmail: "Sign Up with Email",
    loginEmail: "Sign In with Email",
    loginBtn: "Sign In to Portal",
    signupBtn: "Create Secure Account"
  },
  es: {
    appTitle: "PAEONIX",
    browse: "Explorar",
    aiAssistant: "Asistente IA",
    saved: "Guardado",
    adminHub: "Panel Admin",
    settings: "Ajustes",
    clinicalEncyclopedia: "Enciclopedia Clínica",
    verifiedSource: "★ Fuente Verificada",
    dailyFocus: "Enfoque Clínico Diario",
    dailyFocusTitle: "Bienestar Cardiovascular y Lípidos",
    dailyFocusDesc: "Explore cómo la dieta, los lípidos orgánicos y la actividad física optimizan la resistencia celular y protegen la elasticidad capilar.",
    learnMore: "Saber más",
    connecting: "Conectando de forma segura a los registros médicos...",
    allTopics: "Todos los temas",
    chronicConditions: "Enfermedades crónicas",
    cardioHealth: "Salud cardiovascular",
    generalWellness: "Bienestar general",
    infectiousDiseases: "Enfermedades infecciosas",
    mentalHealth: "Salud mental",
    searchPlaceholder: "Buscar síntomas, condiciones, medicamentos...",
    bookmarkTabTitle: "Biblioteca de recursos guardados",
    bookmarkTabDesc: "Su repositorio curado de material de referencia médica",
    noSavedTitle: "No hay artículos guardados",
    noSavedDesc: "Lea artículos en la pestaña Explorar y haga clic en el ícono de marcador para guardarlos para referencia médica sin conexión.",
    chatHeader: "Agente Educativo de IA de PAEONIX",
    chatSub: "Respuestas Médicas Clínicas de Confianza",
    chatPlaceholder: "Pregunte sobre síntomas, prevención o terminología médica...",
    chatDisclaimer: "Descargo de responsabilidad: esta herramienta educativa no sustituye el consejo, diagnóstico o tratamiento clínico profesional.",
    appSettings: "Ajustes de la aplicación",
    managePrefs: "Administrar preferencias de PAEONIX",
    themeCustomization: "Personalización del tema",
    langRegional: "Idioma y región",
    preferredLang: "Idioma preferido",
    pushNotifications: "Notificaciones push",
    notifyDesc: "Reciba alertas sobre actualizaciones médicas",
    accountSecurity: "Seguridad de la cuenta",
    changePwd: "Cambiar contraseña de seguridad",
    currentPwd: "Contraseña actual",
    newPwd: "Nueva contraseña",
    confirmNewPwd: "Confirmar nueva",
    updatePwd: "Actualizar contraseña",
    signOut: "Cerrar sesión de PAEONIX",
    buildVersion: "Versión de compilación de la plataforma:",
    emailPlaceholder: "Dirección de correo electrónico del paciente",
    pwdPlaceholder: "Contraseña de seguridad",
    dontHaveAccount: "¿No tiene una cuenta segura de paciente?",
    alreadyHaveAccount: "¿Ya estás registrado?",
    createAccount: "Crear registro de paciente",
    loginHeader: "Acceder al portal seguro del paciente",
    signupHeader: "Registrar perfil clínico seguro",
    oauthOption: "O inicie sesión de forma segura a través de proveedores verificados",
    signUpEmail: "Registrarse con correo electrónico",
    loginEmail: "Iniciar sesión con correo electrónico",
    loginBtn: "Iniciar sesión en el portal",
    signupBtn: "Crear cuenta segura"
  },
  fr: {
    appTitle: "PAEONIX",
    browse: "Parcourir",
    aiAssistant: "Assistant IA",
    saved: "Enregistré",
    adminHub: "Admin Hub",
    settings: "Paramètres",
    clinicalEncyclopedia: "Encyclopédie Clinique",
    verifiedSource: "★ Source Vérifiée",
    dailyFocus: "Focus Clinique Quotidien",
    dailyFocusTitle: "Bien-être Cardiovasculaire et Lipides",
    dailyFocusDesc: "Découvrez comment l'alimentation, les lipides organiques et l'activité physique optimisent l'endurance cellulaire et protègent l'élasticité capillaire.",
    learnMore: "En savoir plus",
    connecting: "Connexion sécurisée aux dossiers médicaux...",
    allTopics: "Tous les sujets",
    chronicConditions: "Maladies chroniques",
    cardioHealth: "Santé cardiovasculaire",
    generalWellness: "Bien-être général",
    infectiousDiseases: "Maladies infectieuses",
    mentalHealth: "Santé mentale",
    searchPlaceholder: "Rechercher des symptômes, des affections, des médicaments...",
    bookmarkTabTitle: "Bibliothèque de ressources enregistrées",
    bookmarkTabDesc: "Votre dépôt de documents de référence médicale",
    noSavedTitle: "Aucun article enregistré",
    noSavedDesc: "Lisez des articles dans l'onglet Parcourir et cliquez sur l'icône de favori pour les enregistrer pour une référence médicale hors ligne.",
    chatHeader: "Agent Éducatif PAEONIX IA",
    chatSub: "Réponses Médicales Cliniques Fiables",
    chatPlaceholder: "Posez des questions sur les symptômes, la prévention ou la terminologie médicale...",
    chatDisclaimer: "Avertissement : cet outil éducatif ne remplace pas un avis clinique professionnel, un diagnostic ou un traitement.",
    appSettings: "Paramètres de l'application",
    managePrefs: "Gérer les préférences de PAEONIX",
    themeCustomization: "Personnalisation du thème",
    langRegional: "Langue et région",
    preferredLang: "Langue préférée",
    pushNotifications: "Notifications push",
    notifyDesc: "Recevoir des alertes sur les mises à jour médicales",
    accountSecurity: "Sécurité du compte",
    changePwd: "Modifier le mot de passe de sécurité",
    currentPwd: "Mot de passe actuel",
    newPwd: "Nouveau mot de passe",
    confirmNewPwd: "Confirmer le nouveau",
    updatePwd: "Mettre à jour le mot de passe",
    signOut: "Se déconnecter de PAEONIX",
    buildVersion: "Version de la plateforme :",
    emailPlaceholder: "Adresse e-mail du patient",
    pwdPlaceholder: "Mot de passe de sécurité",
    dontHaveAccount: "Vous n'avez pas de compte patient sécurisé ?",
    alreadyHaveAccount: "Déjà inscrit ?",
    createAccount: "Créer un dossier patient",
    loginHeader: "Accéder au portail patient sécurisé",
    signupHeader: "Enregistrer un profil clinique sécurisé",
    oauthOption: "Ou connectez-vous en toute sécurité via des fournisseurs vérifiés",
    signUpEmail: "S'inscrire par e-mail",
    loginEmail: "Se connecter par e-mail",
    loginBtn: "Se connecter au portail",
    signupBtn: "Créer un compte sécurisé"
  },
  ar: {
    appTitle: "PAEONIX",
    browse: "تصفح المواضيع",
    aiAssistant: "المساعد الذكي",
    saved: "المحفوظات",
    adminHub: "لوحة التحكم",
    settings: "الإعدادات",
    clinicalEncyclopedia: "الموسوعة السريرية",
    verifiedSource: "★ مصدر معتمد",
    dailyFocus: "التركيز السريري اليومي",
    dailyFocusTitle: "صحة القلب والأوعية الدموية والدهون",
    dailyFocusDesc: "استكشف كيف يعمل النظام الغذائي والدهون العضوية والنشاط البدني على تحسين القدرة الخلوية والحفاظ على مرونة الشعيرات الدموية.",
    learnMore: "تعلم المزيد",
    connecting: "الاتصال بأمان بالسجلات الطبية الخاصة بك...",
    allTopics: "جميع المواضيع",
    chronicConditions: "الأمراض المزمنة",
    cardioHealth: "صحة القلب والأوعية الدموية",
    generalWellness: "الصحة العامة",
    infectiousDiseases: "الأمراض المعدية",
    mentalHealth: "الصحة النفسية",
    searchPlaceholder: "البحث عن الأعراض، الحالات الصحية، الأدوية...",
    bookmarkTabTitle: "مكتبة المصادر المحفوظة",
    bookmarkTabDesc: "مستودعك المنسق للمواد المرجعية الطبية",
    noSavedTitle: "لا توجد مقالات محفوظة",
    noSavedDesc: "اقرأ المقالات في علامة التبويب تصفح وانقر على أيقونة الإشارة المرجعية لحفظها للرجوع إليها طبياً دون اتصال بالإنترنت.",
    chatHeader: "بايونيكس وكيل التعليم الذكي",
    chatSub: "إجابات طبية سريرية موثوقة",
    chatPlaceholder: "اسأل عن الأعراض أو الوقاية أو المصطلحات الطبية...",
    chatDisclaimer: "تنبيه: هذه الأداة التعليمية ليست بديلاً عن الاستشارة الطبية السريرية المهنية أو التشخيص أو العلاج.",
    appSettings: "إعدادات التطبيق",
    managePrefs: "إدارة تفضيلات بايونيكس (PAEONIX)",
    themeCustomization: "تخصيص المظهر",
    langRegional: "اللغة والمنطقة",
    preferredLang: "اللغة المفضلة",
    pushNotifications: "التنبيهات العاجلة",
    notifyDesc: "تلقي تنبيهات بشأن التحديثات الطبية",
    accountSecurity: "أمان الحساب",
    changePwd: "تغيير كلمة مرور الأمان",
    currentPwd: "كلمة المرور الحالية",
    newPwd: "كلمة المرور الجديدة",
    confirmNewPwd: "تأكيد كلمة المرور",
    updatePwd: "تحديث كلمة المرور",
    signOut: "تسجيل الخروج من بايونيكس (PAEONIX)",
    buildVersion: "نسخة بناء المنصة:",
    emailPlaceholder: "البريد الإلكتروني للمريض",
    pwdPlaceholder: "كلمة مرور الأمان",
    dontHaveAccount: "ليس لديك حساب مريض آمن؟",
    alreadyHaveAccount: "مسجل بالفعل؟",
    createAccount: "إنشاء سجل مريض جديد",
    loginHeader: "الدخول إلى بوابة المريض الآمنة",
    signupHeader: "تسجيل ملف سريري آمن",
    oauthOption: "أو تسجيل الدخول بأمان عبر الخدمات المعتمدة",
    signUpEmail: "تسجيل باستخدام البريد الإلكتروني",
    loginEmail: "تسجيل الدخول بالبريد الإلكتروني",
    loginBtn: "تسجيل الدخول إلى البوابة",
    signupBtn: "إنشاء حساب آمن"
  }
};

export function useTranslation(lang: string = "en") {
  const t = (key: keyof typeof TRANSLATIONS.en): string => {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || String(key);
  };
  return { t };
}
